# Generated by Django 4.0.4 on 2022-04-12 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Giohang',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tongtien', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Nguoidung',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taikhoan', models.CharField(max_length=50)),
                ('hoten', models.CharField(max_length=100)),
                ('matkhau', models.CharField(max_length=30)),
                ('diachi', models.CharField(max_length=300)),
                ('ngaysinh', models.DateField(null=True)),
                ('email', models.CharField(max_length=100)),
                ('sodienthoai', models.CharField(max_length=11)),
                ('vaitro', models.CharField(default='khachhang', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nhaxuatban',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tennhaxuatban', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tacgia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tentacgia', models.CharField(max_length=200)),
                ('diachi', models.CharField(max_length=500, null=True)),
                ('namsinh', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theloai',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tentheloai', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Thongtinthanhtoan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thoigianthanhtoan', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('api_nguoidung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.nguoidung')),
            ],
        ),
        migrations.CreateModel(
            name='Khachhang',
            fields=[
                ('api_nguoidung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.nguoidung')),
            ],
        ),
        migrations.CreateModel(
            name='Nhanvien',
            fields=[
                ('api_nguoidung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.nguoidung')),
            ],
        ),
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tensach', models.CharField(max_length=200)),
                ('giasach', models.FloatField()),
                ('namphathanh', models.DateField(null=True)),
                ('soluong', models.IntegerField(default=0)),
                ('api_nhaxuatban', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.nhaxuatban')),
                ('api_tacgia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tacgia')),
                ('api_theloai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.theloai')),
            ],
        ),
        migrations.CreateModel(
            name='Donhang',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('diachi', models.CharField(max_length=300)),
                ('ngaydat', models.DateTimeField(auto_now_add=True)),
                ('tongtien', models.FloatField()),
                ('isThanhtoan', models.BooleanField(default=False)),
                ('isHoanthanh', models.BooleanField(default=False)),
                ('thongtinthanhtoan', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.thongtinthanhtoan')),
                ('api_khachhang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='Sanphamtronggio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('soluong', models.IntegerField(default=1)),
                ('api_giohang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.giohang')),
                ('api_sach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sach')),
            ],
            options={
                'unique_together': {('api_giohang', 'api_sach')},
            },
        ),
        migrations.CreateModel(
            name='Sanphamdadat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('soluong', models.IntegerField(default=1)),
                ('giaban', models.FloatField()),
                ('api_donhang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.donhang')),
                ('api_sach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sach')),
            ],
            options={
                'unique_together': {('api_donhang', 'api_sach')},
            },
        ),
        migrations.AddField(
            model_name='giohang',
            name='api_khachhang',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.khachhang'),
        ),
    ]
