# Generated by Django 4.0.4 on 2022-04-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_nguoidung_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tacgia',
            name='namsinh',
            field=models.IntegerField(null=True),
        ),
    ]
