# Generated by Django 4.0.4 on 2022-04-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_sach_namphathanh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giohang',
            name='tongtien',
            field=models.FloatField(default=0, null=True),
        ),
    ]
