# Generated by Django 4.0.4 on 2022-04-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_giohang_tongtien'),
    ]

    operations = [
        migrations.AddField(
            model_name='sach',
            name='hinhanh',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
