# Generated by Django 4.0.4 on 2022-04-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sach_hinhanh'),
    ]

    operations = [
        migrations.AddField(
            model_name='sach',
            name='mota',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
