# Generated by Django 4.0.4 on 2022-04-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_sach_mota'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='hoten',
            field=models.CharField(default='thanh', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donhang',
            name='sodienthoai',
            field=models.CharField(default=291029, max_length=11),
            preserve_default=False,
        ),
    ]
